version: '3.8'
services:
  angular:
    container_name: test-angular-app
    image: test-angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx ng serve --host 0.0.0.0 --disable-host-check